#!/bin/bash
# VPS检查命令脚本
# 在VPS上逐步执行以下命令来诊断和修复问题

echo "🔍 VPS问题诊断和修复命令"
echo "=================================================="

echo ""
echo "📋 第一步：系统基本检查"
echo "------------------------------------------------"
echo "# 检查系统信息"
echo "uname -a"
echo "uptime"
echo "df -h"
echo ""
echo "# 检查Python版本"
echo "python3 --version"
echo ""
echo "# 检查当前目录和文件"
echo "pwd"
echo "ls -la"

echo ""
echo "🐳 第二步：Docker服务检查"
echo "------------------------------------------------"
echo "# 检查Docker服务状态"
echo "systemctl status docker"
echo ""
echo "# 检查Docker容器"
echo "docker ps -a"
echo ""
echo "# 检查Docker Compose状态"
echo "docker-compose ps"

echo ""
echo "🔌 第三步：端口占用检查"
echo "------------------------------------------------"
echo "# 检查8080端口占用"
echo "lsof -i:8080"
echo ""
echo "# 检查3306端口占用"
echo "lsof -i:3306"
echo ""
echo "# 检查所有监听端口"
echo "netstat -tlnp"

echo ""
echo "🐍 第四步：Python进程检查"
echo "------------------------------------------------"
echo "# 检查所有Python进程"
echo "ps aux | grep python"
echo ""
echo "# 检查web_server.py进程"
echo "ps aux | grep web_server.py"
echo ""
echo "# 检查deepseekok2.py进程"
echo "ps aux | grep deepseekok2.py"

echo ""
echo "🔗 第五步：API测试"
echo "------------------------------------------------"
echo "# 测试本地API"
echo "curl -s http://localhost:8080/api/dashboard | head -100"
echo ""
echo "# 测试健康检查"
echo "curl -s http://localhost:8080/api/health"
echo ""
echo "# 测试主页"
echo "curl -s http://localhost:8080/ | head -50"

echo ""
echo "📄 第六步：日志检查"
echo "------------------------------------------------"
echo "# 检查日志文件"
echo "ls -la *.log"
echo ""
echo "# 查看web_server.log"
echo "tail -20 web_server.log"
echo ""
echo "# 查看系统日志中的相关错误"
echo "journalctl -u docker --since '1 hour ago' | tail -20"

echo ""
echo "🔧 第七步：问题修复（如果发现问题）"
echo "------------------------------------------------"
echo "# 停止Docker服务（如果冲突）"
echo "docker-compose down"
echo ""
echo "# 强制清理端口8080"
echo "lsof -ti:8080 | xargs kill -9"
echo ""
echo "# 清理Python进程"
echo "pkill -f web_server.py"
echo "pkill -f deepseekok2.py"
echo ""
echo "# 等待进程完全退出"
echo "sleep 5"
echo ""
echo "# 验证端口释放"
echo "lsof -i:8080"
echo ""
echo "# 启动web服务器"
echo "nohup python3 web_server.py > web_server.log 2>&1 &"
echo ""
echo "# 等待服务启动"
echo "sleep 5"
echo ""
echo "# 验证服务启动"
echo "ps aux | grep web_server.py"
echo "lsof -i:8080"
echo ""
echo "# 测试API"
echo "curl -s http://localhost:8080/api/dashboard"

echo ""
echo "🎯 第八步：最终验证"
echo "------------------------------------------------"
echo "# 访问网站检查"
echo "echo '访问: https://arena.aimaventop.com/flow/'"
echo ""
echo "# 如果问题仍然存在，检查以下："
echo "echo '1. 检查.env文件配置'"
echo "cat .env | grep -E '(PORT|MYSQL|DEEPSEEK|OKX)'"
echo ""
echo "echo '2. 检查数据库文件'"
echo "ls -la *.db"
echo ""
echo "echo '3. 检查paper_trading.py修复'"
echo "grep -A 10 -B 5 'price is None or amount is None' paper_trading.py"
echo ""
echo "echo '4. 重启整个VPS（最后手段）'"
echo "# sudo reboot"

echo ""
echo "=================================================="
echo "💡 使用说明："
echo "1. 将上述命令复制到VPS终端中逐步执行"
echo "2. 根据输出结果判断问题所在"
echo "3. 执行相应的修复命令"
echo "4. 如果自动修复失败，可以运行："
echo "   python3 vps_direct_diagnosis.py"
echo "   python3 vps_auto_fix.py"
echo "=================================================="